stages:
  - build

variables:
  FLUTTER_VERSION: "3.44.0"
  PUB_CACHE: "$CI_PROJECT_DIR/.pub-cache"

cache:
  paths:
    - .pub-cache/
    - .dart_tool/
    - build/

build_linux:
  stage: build

  image: ghcr.io/cirruslabs/flutter:${FLUTTER_VERSION}

  tags:
    - linux

  script:
    - ./build_linux.sh

  artifacts:
    name: "linux-build-$CI_COMMIT_SHORT_SHA"
    paths:
      - build/email-alias.deb
      - build/email-alias.rpm
    expire_in: 7 days

  only:
    - main
    - master
    - develop
